main: com.gmail.justbru00.epic.ban.requests.main.Main
version: 1.3
name: EpicBanRequests
api-version: 1.13
authors: [Justin Brubaker, JustBru00]
commands:
  requestban:
    description: Requests a ban from higher level staff.
